name: ðŸš€ CI/CD with Maven and Docker

on: [push]
permissions:
  packages: write
  contents: read
jobs:
  build:
    name: Build with Maven and Deploy with Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:

      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # https://github.com/marketplace/actions/snyk
      - name: Run Snyk to check for vulnerabilities
        uses: actions/checkout@master
        # uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test

      # x https://github.com/marketplace/actions/java-maven-release
      - name: Increment Maven Patch Number
        uses: qcastel/github-actions-maven-release@master
        with:
          version-major: false
          version-minor: false
          version-patch: true

      # Maven
      - name: Get project version
        run: |
          echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Test and build with Maven
        run: mvn clean package

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: 'linux/amd64,linux/arm64'
          tags: hakktastic/learn-github-actions:${{ env.POM_VERSION }}

      # https://github.com/marketplace/actions/aqua-security-trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/hakktastic/learn-github-actions:${{ env.POM_VERSION }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
